const songs=[
  {
    name: "A Road to Find You",
    img: "A Road to Find You",
    title: "A Road to Find You",
    artist: "Chris Zurich",
  },
  {
    name: "BLACKPINK - So Hot (feat. Nicki Minaj)",
    img:"BLACKPINK - So Hot (feat. Nicki Minaj)", 
    title: "So Hot",
    artist: "Blackpink ft. Nicki Minaj",
  },
  {
    name: "Pretty Savage",
    img: "The Album",
    title: "Pretty Savage",
    artist: "Blackpink",
  },
  {
    name: "Bet You Wanna ft. Cardi B",
    img: "The Album",
    title: "bet you wanna",
    artist: "Blackpink ft. Cardi B",
  },
  {
    name: "BLACKPINK – ‘Lovesick Girls’ M V",
    img: "The Album",
    title: "lovesick girls",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK - AS IF IT S YOUR LAST (마지막처럼) [HAN ROM ENG Color Coded]",
    img: "Blackpink in your area",
    title: "as if it is your last",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK - How You Like That M V",
    img: "The Album",
    title: "how you like that",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK - PLAYING WITH FIRE (불장난) [Color Coded Han Rom Eng]",
    img:"Blackpink in your area",
    title: "playing with fire",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK - STAY (With English Rap) (Color Coded Han Rom Eng) rosie",
    img: "Blackpink in your area",
    title: "stay",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK – Whistle (휘파람) (Color Coded Han Rom Eng) by Yankat",
    img: "Blackpink in your area",
    title: "whistle",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK Crazy Over You (블랙핑크 Crazy Over You 가사) [Color Coded Eng]",
    img: "The Album",
    title: "crazy over you",
    artist: "Blackpink",
  },
  {
    name: "JENNIE - SOLO M V",
    img: "JENNIE - SOLO M V",
    title: "solo",
    artist: "jennie",
  },
  {
    name: "Love To Hate Me",
    img: "The Album",
    title: "Love To Hate Me",
    artist: "Blackpink",
  },
  {
    name: "Really",
    img: "Square Up",
    title: "Really",
    artist: "Blackpink",
  },
  {
    name: "You Never Know",
    img: "The Album",
    title: "You Never Know",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK – DDU-DU DDU-DU (Color Coded)",
    img: "Square Up",
    title: "Ddu-du ddu-du",
    artist: "Blackpink",
  },
  {
    name: "BLACKPINK – BOOMBAYAH (붐바야) (Color Coded Han Rom Eng) by Yankat",
    img: "Blackpink in your area",
    title: "boombayah",
    artist: "Blackpink",
  },
  {
    name: "Can t Help Falling In Love",
    img: "Can t Help Falling In Love",
    title: "Can't Help Falling ",
    // title: "Can't Help Falling In Love",
    artist: "Haley Reinhart",
  },
  {
    name: "River",
    img: "Church Of Scars",
    title: "River",
    artist: "Bishop Briggs",
  },
  {
    name: "When We Were Kids",
    img: "Bangers only",
    title: "When We Were Kids",
    artist: "Bangers Only x Zeegs x Preston Pablo",
  },
  {
    name: "No Time To Die",
    img: "no time to die",
    title: "No Time To Die",
    artist: "Billie Eilish",
  },
  {
    name: "This Is How You Walk On(From “Gifted”)",
    img: "gifted",
    title: "This Is How You Walk On",
    artist: "Gary Lightbody & Johnny McDaid",
  },
  {
    name: "Afterglow",
    img: "afterglow",
    title: "Afterglow",
    artist: "Ed sheeran",
  },
  {
    name: "willow",
    img: "evermore",
    title: "Willow",
    artist: "Taylor Swift",
  },
  {
    name: "You re The One ",
    img: "the vogues",
    title: "You're The One",
    artist: "The Vogues",
  },
  {
    name: "Happier",
    img: "divide",
    title: "Happier",
    artist: "Ed Sheeran",
  },
  {
    name: "Dive",
    img: "divide",
    title: "Dive",
    artist: "Ed Sheeran",
  },
  {
    name: "Kiss Me",
    img: "+",
    title: "Kiss Me",
    artist: "Ed Sheeran",
  },
  {
    name: "Kannala Kannala(Thani Oruvan)",
    img: "thani oruvan",
    title: "Kannala Kannala",
    artist: "Hip Hop Tamizha",
  },
  {
    name: "comethru",
    img: "summer,",
    title: "comethru",
    artist: "Jeremy Zucker",
  },
  {
    name: "Nenjukkul Peidhidum(Vaaranam Aayiram)",
    img: "vaaranam-aayiram",
    title: "Nenjukkul Peidhidum",
    artist: "Harris Jayaraj",
  },
  {
    name: "Aashiyan",
    img: "barfi",
    title: "Aashiyan",
    artist: "",
  },
  {
    name: "Engleesu Lovesu",
    img: "pakkiri",
    title: "Engleesu Lovesu",
    artist: "",
  },
  {
    name: "Last Christmas",
    img: "last christmas",
    title: "Last Christmas",
    artist: "Taylor Swift",
  },
  {
    name: "Thinking Out Loud",
    img: "x",
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
  },
  {
    name: "Hold On",
    img: "holdon",
    title: "Hold On",
    artist: "Chord Overstreet",
  },
  {
    name: "Play Date",
    img: "crybaby",
    title: "Play Date",
    artist: "Melanie Martinez",
  },
  {
    name: "Trampoline",
    img: "Trampoline",
    title: "Trampoline",
    artist: "SHAED x ZAYN",
  },
  {
    name: "Hi-Lo (Hollow)",
    img: "Church Of Scars",
    title: "Hi-Lo (Hollow)",
    artist: "Bishop Briggs",
  },

  
];

